### ISSUE TITLE
Vulnerability Report(1): Unauthorized Operation(Bypassed SPF Restrictions)

### ISSUE THREAD

**Issue by aliraza7989** [okcashpro/okcash.co.website#1]
![Screenshot_2023-02-04_06_58_56](https://user-images.githubusercontent.com/106284743/216766535-0472442b-cc40-4f64-803d-b07769af746e.png)
**Description:**
The attacker can send a legitimate email to any person without even your permission and knowledge; besides this, the victim won't recognize it as real or fake. A fake email shows the DP(display pic) of your Email. 

**Vulnerable Domains:**
https://okcash.org/
https://okcash.io/
https://oktoken.cash/
https://okcash.co/
https://okcash.news/

It is a big threat to a company regarding your market reputation as well, as attackers could spread fake rumors which could directly abash you in the market, as you are aware of it while doing online business the only matters a lot is security and especially when it comes to those online businesses where transactions are involved. If you want to groom your business, you must be a step ahead of the market and strive to improve your website's flaw. Customers already have several alternatives; therefore, the chances of losing old customers enhanced upon discussing fake rumors spread by hackers because the public is going to believe in those rumors, it is received by the legitimate email of   https://okcash.co/. Although the attacker can ask money from your customers/clients on behalf of  https://okcash.co/ or pretending to be a staff member of  https://okcash.co/ attackers can ask for account credentials from users pretending to be members of   https://okcash.co/   security staff. As you know, we have scripts of multiple software like a cyber gate to generate malicious URLs. When the victim clicks on that URL, his whole system will be remotely under the control of a hacker without even his information and knowledge. Now the question arises why the victim clicks on the malicious URL? The answer is,   https://okcash.co/    has a good market reputation; therefore, when the victim receives a legitimate email from  https://okcash.co// ,he is going to open the URL. Hackers can provide an attractive opportunity(trap) to make him click on that malicious URL.

Many other scenarios are possible. 

I'm able to send a legitimate email to you.

**Comment by aliraza7989** [comment]
Here is my BSC wallet address for reward: 0xda8DFdfCBE116557d9743Dc09B3bfae3A7f8B604

**Comment by oktoshi** [comment]
Email masks can be done with any email address. So everyone on the whole web is at risk of this. Hence security measures like security codes for original emails are now available in some services/mail/companies.
None of the domains are used to mail, mass mail, or anything other than getting feedback and developer inquiries.
So this world wide web issue does not affect the OK sites; these sites are for information purposes only; they don't send mail, and they don't get mail.
Thanks for your assessment; in regards to this not being a security risk for the OK environment, we are closing this issue.

**Comment by aliraza7989** [comment]
Thank you for responding.

This is not really right that anyone can send email from any domain because if you don't add protection on your domain it will remain vulnerable but I can assure you follow my recommendation then it will be fixed and remain no longer vulnerable. There are many companies who fixed this vulnerability because it impose a bad impact on company reputation, if people start receiving emails from your company and in which attacker is spreading fake rumors against your project.

I can share some domains which are not vulnerable to this vulnerability such as:
https://makerdao.com/en/
https://www.kucoin.com/
https://smartvalor.com/

Recommendation:
You need to add SPF,DKIM and DMARC in your domain setting and while adding DMARC please add p tag as "reject" so the fake emails will neither go to inbox nor in spam.

I think this finding is eligible for reward.

Thank you
